FROM alpine:latest AS builder
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN apk add --no-cache upx
COPY a2a /artifacts/a2a
RUN upx --best --lzma /artifacts/a2a

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /artifacts/a2a /a2a
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/a2a"]
