version = 1

[install]
go.pkg-path = "go"
go.version = "^1.25"

go-task.pkg-path = "go-task"
go-task.version = "^3.45.4"

[hook]
on-activate = """
  export GOENV="$FLOX_ENV_CACHE/goenv"

  go get .
"""
