schema-version = "1.12.0"

[install]
go.pkg-path = "go"
go.version = "^1.26.2"
go-task.pkg-path = "go-task"
go-task.version = "^3.48.0"
infer.flake = "github:inference-gateway/cli/v0.120.0"
claude-code.pkg-path = "claude-code"
claude-code.version = "^2.1.158"
claude-code.pkg-group = "claude-code"
codex.pkg-path = "codex"
codex.version = "^0.135.0"
codex.pkg-group = "codex"

[hook]
on-activate = """
  export GOENV="$FLOX_ENV_CACHE/goenv"

  go get .
"""
