name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Task
        run: |
          curl -s https://taskfile.dev/install.sh | sh -s -- -b /usr/local/bin v3.45.4

      - name: Install golangci-lint
        run: |
          curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v2.5.0

      - name: Install Go tools
        run: |
          go install github.com/maxbrunsfeld/counterfeiter/v6@v6.11.2

      - name: Generate
        run: task generate

      - name: Run Tidy
        run: task tidy

      - name: Check dirty files
        run: |
          if ! git diff --exit-code; then
            echo "There are uncommitted changes. Please commit or stash them before running the workflow."
            exit 1
          fi

      - name: Lint
        run: task lint

      - name: Build
        run: task build

      - name: Test
        run: task test
